# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+01:00"
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
#       - name: Build it (Release)
#         run: msbuild /t:Build /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None
      - name: Build it (Debug)
        run: msbuild /t:Build /p:Configuration=Debug
      - uses: actions/upload-artifact@v2
        with:
          name: P2P-Debug-"${{ steps.current-time.outputs.formattedTime }}"
          path: P2PLauncher/bin/Debug/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            P2PLauncher/bin/Debug/P2PLauncher.exe
